#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <fcntl.h>
#include <string.h>

/*
 *  Usage: ./multiproc numProcs inputFile0 inputFile1 ... inputFile(procNum-1)
 *
 */

int main(int argc, char* argv[])
{
    // argv1 is number of processes to run
    // subsequent argvs are file for each process to fuzz

    char* args[10];
    int st;

    // Write results to file.out.$i
    int i;
    for (i = 0; i < atoi(argv[1]); i++) {

        if (fork() == 0) {

            close(1);
            char file[100];
            file[0] = '\0';
            strcat(file, "output.");
            char buf[10];
            //itoa(i, buf);
            snprintf(buf, 10, "%d", i);
            strcat(file, buf);
            int fd = open(file, O_WRONLY | O_CREAT, 0666);

            args[0] = "../pin/pin";
            args[1] = "-t";
            args[2] = "obj-ia32/MyPinTool.so"; 
            args[3] = "--";
            args[4] = "./simpleCrackme";
            args[5] = argv[2 + i];      // input file, generated by python driver
            args[6] = NULL;

            execv(args[0], args);

        }

    }

    for (i = 0; i < atoi(argv[1]); i++) {
        wait(&st);
    }

}

