#include<stdio.h>
#include<unistd.h>
#include<stdlib.h>

int main(int argc, char* argv[])
{
    // argv1 is number of processes to run
    // subsequent argvs are file for each process to fuzz

    char* args[10];
    int st;

    int i;
    for (i = 0; i < atoi(argv[1]); i++) {

        if (fork() == 0) {
            args[0] = "../pin/pin";
            args[1] = "-t";
            args[2] = "obj-ia32/MyPinTool.so"; 
            args[3] = "--";
            args[4] = "./simpleCrackme";
            args[5] = argv[2];      // input file, generated by python driver
            args[6] = NULL;

            execv(args[0], args);

        }

    }
    wait(&st);


}
